@startuml
scale 1920x1080

title __DISSENYSOFTWARE3's Class Diagram__\n


    class AppUBFLIXParty {
    }



  controller.Controller o-- model.CarteraClients : carteraClients
  controller.Controller o-- resources.service.DataService : dataService
  controller.Controller o-- resources.service.AbstractFactoryData : factory
  controller.Controller o-- model.carteraSeries : llistaSeries
  resources.dao.MOCK.DAOClientMOCK .up.|> resources.dao.DAOClient
  resources.dao.MOCK.DAOEpisodiMOCK .up.|> resources.dao.DAOEpisodi
  resources.dao.MOCK.DAOFollowersMOCK .up.|> resources.dao.DAOFollowers
  resources.dao.MOCK.DAOFollowingMOCK .up.|> resources.dao.DAOFollowing
  resources.dao.MOCK.DAOMyListMOCK .up.|> resources.dao.DAOMyList
  resources.dao.MOCK.DAOPostMOCK .up.|> resources.dao.DAOPost
  resources.dao.MOCK.DAOSerieMOCK .up.|> resources.dao.DAOSerie
  resources.dao.MOCK.DAOTemporadaMOCK .up.|> resources.dao.DAOTemporada
  resources.dao.MOCK.DAOUsuariMOCK .up.|> resources.dao.DAOUsuari
  resources.dao.MOCK.DAOValoracioEstrellaMOCK .up.|> resources.dao.DAOValoracioEstrella
  resources.dao.MOCK.DAOValoracioThumbMOCK .up.|> resources.dao.DAOValoracioThumb
  resources.dao.MOCK.DAOWatchingMOCK .up.|> resources.dao.DAOWatching
  resources.service.DataService o-- resources.dao.DAOEpisodi : EpisodiDAO
  resources.service.DataService o-- resources.dao.DAOTemporada : TemporadaDAO
  resources.service.DataService o-- resources.dao.DAOValoracioEstrella : ValoracioEstrellaDAO
  resources.service.DataService o-- resources.dao.DAOValoracioThumb : ValoracioThumbDAO
  resources.service.DataService o-- resources.dao.DAOClient : clientDAO
  resources.service.DataService o-- resources.dao.DAOFollowers : followersDAO
  resources.service.DataService o-- resources.dao.DAOFollowing : followingDAO
  resources.service.DataService o-- resources.dao.DAOMyList : mylistDAO
  resources.service.DataService o-- resources.dao.DAOPost : postDAO
  resources.service.DataService o-- resources.dao.DAOSerie : serieDAO
  resources.service.DataService o-- resources.dao.DAOUsuari : usuariDAO
  resources.service.DataService o-- resources.dao.DAOWatching : watchingDAO
  resources.service.FactoryMOCK .up.|> resources.service.AbstractFactoryData
  view.FerPost -up-|> javax.swing.JDialog
  view.FormEpisodi -up-|> javax.swing.JDialog
  view.FormPerfilUsuari -up-|> javax.swing.JFrame
  view.FormReproduccio -up-|> javax.swing.JDialog
  view.FormReproductorVideo o-- view.MediaControl : mediaControl
  view.FormUser o-- controller.Controller : controlador
  view.FrmLogIn o-- controller.Controller : controlador
  view.FrmRegistre o-- controller.Controller : controlador
  view.FrmRegistre o-- controller.Controller : controlador
  view.FrmRegistre o-- controller.Controller : controlador
  view.FrmValoracio o-- controller.Controller : controller
  view.MediaControl -up-|> javafx.scene.layout.BorderPane
  view.UBFLIXParty o-- controller.Controller : controlador
  model.Client--*model.CarteraClients
  model.Usuari--*model.Client
  model.Post--*model.Usuari
  model.Serie--*model.carteraSeries
  model.Temporada--*model.Serie
  model.Episodi--*model.Temporada
  model.valoracioEstrella--*model.Episodi
  model.valoracioThumb--*model.Episodi
  model.Watching--*model.Episodi


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml